name: End 2 End test

on:
  push:
    branches:
      - '*'

jobs:
  end2end:
    strategy:
      matrix:
        phpver: [5.6, "7.0", 7.1, 7.2, 7.3, 7.4, "8.0", 8.1, 8.2]

    runs-on: ubuntu-latest
    container: php:${{ matrix.phpver }}-alpine
    env:
      TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
      CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system requirements
        run: |
          apk add make
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install depedencies
        run: composer install && composer show

      - name: Run E2E test
        run: make e2e
